# Generated by Django 4.1.3 on 2022-11-28 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=10)),
                ('password', models.BinaryField(max_length=60)),
                ('ssl', models.CharField(max_length=60)),
            ],
            options={
                'db_table': 'users',
            },
        ),
    ]
