# Generated by Django 4.1.3 on 2022-11-30 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0002_rename_ssl_user_ssn'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='ssn',
            field=models.BinaryField(max_length=256),
        ),
    ]
