# Generated by Django 4.1.3 on 2022-12-02 18:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0004_alter_transaction_index_together'),
        ('auth', '0003_alter_user_ssn'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='name',
        ),
        migrations.RemoveField(
            model_name='user',
            name='ssn',
        ),
        migrations.AddField(
            model_name='user',
            name='first_name',
            field=models.CharField(default='김', max_length=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='last_name',
            field=models.CharField(default='rla', max_length=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='username',
            field=models.CharField(max_length=10, null=True),
        )
    ]
