# Generated by Django 4.1.3 on 2022-12-02 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0005_alter_user_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='credit',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
