# Generated by Django 4.1.3 on 2022-12-02 01:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0003_remove_transaction_date_remove_transaction_time_and_more'),
    ]

    operations = [
        migrations.AlterIndexTogether(
            name='transaction',
            index_together={('account', 'timestamp')},
        ),
    ]
