# Generated by Django 4.1.3 on 2022-12-03 15:44

from django.db import migrations, models
import django.db.models.expressions
import django.db.models.functions.datetime


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0004_alter_transaction_index_together'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='account',
            constraint=models.CheckConstraint(check=models.Q(('balance__gte', 0)), name='accounts_balance_not_less_than_zero'),
        ),
        migrations.AddConstraint(
            model_name='transaction',
            constraint=models.CheckConstraint(check=models.Q(('amount__gte', 0)), name='tansactions_amount_not_less_than_zero'),
        ),
        migrations.AddConstraint(
            model_name='transaction',
            constraint=models.CheckConstraint(check=models.Q(('balance__gte', 0)), name='tansactions_balance_not_less_than_zero'),
        ),
        migrations.AddConstraint(
            model_name='transaction',
            constraint=models.CheckConstraint(check=models.Q(('timestamp__lte', django.db.models.expressions.CombinedExpression(models.Value(1000000), '*', django.db.models.expressions.CombinedExpression(models.Func(django.db.models.functions.datetime.Now(), function='UNIXEPOCH'), '+', models.Value(10))))), name='timestamp_not_more_than_now'),
        ),
    ]
