# Generated by Django 4.1.3 on 2022-12-03 15:47

import apps.transaction.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0005_account_accounts_balance_not_less_than_zero_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='timestamp',
            field=models.PositiveBigIntegerField(default=apps.transaction.models.time_now),
        ),
    ]
